# Generated by Django 6.0.7 on 2026-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
